### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by sergeiown** [131/trayicon#5]
Hey there!

When I use [trayicon](https://github.com/131/trayicon) I sometimes get an error with no specific frequency or dependence on a specific event:

`error.message`
```javascript
Unhandled error. ('Invalid exit code 3762507597')
```

`error.stack`
```javascript
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Invalid exit code 3762507597')
    at Tray.emit (node:events:509:17)
    at ChildProcess.<anonymous> (index.js:115:16)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
    
3762507597 corresponds to a Windows error which is often associated with incorrect operation of graphic components or missing libraries. I would be grateful for information: what exactly is the cause and how to deal with it.

_Originally posted by @sergeiown in https://github.com/131/trayicon/discussions/4_

**Comment by sergeiown** [comment]
More debugging information:

```javascript
  trayicon:info Server listening on port 51471 +0ms
  trayicon:info Spawning rsrcs\trayicon.exe [ 51471 ] +1ms
  trayicon:info Waiting for client +7ms
Got port 51471
Connecting to 51471
  trayicon:info Got client +112ms
Connected to 51471
Begin receive loop
Unhandled Exception: System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TrayIcon.TrayContext.ReceiveCallback(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
  trayicon:error Error on rsrcs\trayicon.exe (exit 3762507597) +56m
```
